// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: discogs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MasterSort int32

const (
	MasterSort_BY_YEAR MasterSort = 0
)

// Enum value maps for MasterSort.
var (
	MasterSort_name = map[int32]string{
		0: "BY_YEAR",
	}
	MasterSort_value = map[string]int32{
		"BY_YEAR": 0,
	}
)

func (x MasterSort) Enum() *MasterSort {
	p := new(MasterSort)
	*p = x
	return p
}

func (x MasterSort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MasterSort) Descriptor() protoreflect.EnumDescriptor {
	return file_discogs_proto_enumTypes[0].Descriptor()
}

func (MasterSort) Type() protoreflect.EnumType {
	return &file_discogs_proto_enumTypes[0]
}

func (x MasterSort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MasterSort.Descriptor instead.
func (MasterSort) EnumDescriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{0}
}

type SaleStatus int32

const (
	SaleStatus_UNKNOWN   SaleStatus = 0
	SaleStatus_FOR_SALE  SaleStatus = 1
	SaleStatus_SOLD      SaleStatus = 2
	SaleStatus_VIOLATION SaleStatus = 3
	SaleStatus_DRAFT     SaleStatus = 4
	SaleStatus_EXPIRED   SaleStatus = 5
)

// Enum value maps for SaleStatus.
var (
	SaleStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "FOR_SALE",
		2: "SOLD",
		3: "VIOLATION",
		4: "DRAFT",
		5: "EXPIRED",
	}
	SaleStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"FOR_SALE":  1,
		"SOLD":      2,
		"VIOLATION": 3,
		"DRAFT":     4,
		"EXPIRED":   5,
	}
)

func (x SaleStatus) Enum() *SaleStatus {
	p := new(SaleStatus)
	*p = x
	return p
}

func (x SaleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SaleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_discogs_proto_enumTypes[1].Descriptor()
}

func (SaleStatus) Type() protoreflect.EnumType {
	return &file_discogs_proto_enumTypes[1]
}

func (x SaleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SaleStatus.Descriptor instead.
func (SaleStatus) EnumDescriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{1}
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_discogs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{0}
}

func (x *Field) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Folder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_discogs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{1}
}

func (x *Folder) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Folder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MasterRelease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterRelease) Reset() {
	*x = MasterRelease{}
	mi := &file_discogs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterRelease) ProtoMessage() {}

func (x *MasterRelease) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterRelease.ProtoReflect.Descriptor instead.
func (*MasterRelease) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{2}
}

func (x *MasterRelease) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MasterRelease) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Pages         int32                  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_discogs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{3}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

type Format struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptions  []string               `protobuf:"bytes,1,rep,name=descriptions,proto3" json:"descriptions,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Format) Reset() {
	*x = Format{}
	mi := &file_discogs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Format) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Format) ProtoMessage() {}

func (x *Format) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Format.ProtoReflect.Descriptor instead.
func (*Format) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{4}
}

func (x *Format) GetDescriptions() []string {
	if x != nil {
		return x.Descriptions
	}
	return nil
}

func (x *Format) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Format) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiscogsUserId int32                  `protobuf:"varint,1,opt,name=discogs_user_id,json=discogsUserId,proto3" json:"discogs_user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	UserToken     string                 `protobuf:"bytes,3,opt,name=user_token,json=userToken,proto3" json:"user_token,omitempty"`
	UserSecret    string                 `protobuf:"bytes,4,opt,name=user_secret,json=userSecret,proto3" json:"user_secret,omitempty"`
	PersonalToken string                 `protobuf:"bytes,5,opt,name=personal_token,json=personalToken,proto3" json:"personal_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_discogs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetDiscogsUserId() int32 {
	if x != nil {
		return x.DiscogsUserId
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetUserToken() string {
	if x != nil {
		return x.UserToken
	}
	return ""
}

func (x *User) GetUserSecret() string {
	if x != nil {
		return x.UserSecret
	}
	return ""
}

func (x *User) GetPersonalToken() string {
	if x != nil {
		return x.PersonalToken
	}
	return ""
}

type Release struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InstanceId      int64                  `protobuf:"varint,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	FolderId        int32                  `protobuf:"varint,3,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Rating          int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Title           string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	MasterId        int64                  `protobuf:"varint,13,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	Condition       string                 `protobuf:"bytes,8,opt,name=condition,proto3" json:"condition,omitempty"`
	SleeveCondition string                 `protobuf:"bytes,9,opt,name=sleeve_condition,json=sleeveCondition,proto3" json:"sleeve_condition,omitempty"`
	Formats         []*Format              `protobuf:"bytes,5,rep,name=formats,proto3" json:"formats,omitempty"`
	Labels          []*Label               `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
	Artists         []*Artist              `protobuf:"bytes,12,rep,name=artists,proto3" json:"artists,omitempty"`
	Notes           map[int32]string       `protobuf:"bytes,10,rep,name=notes,proto3" json:"notes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ReleaseDate     int64                  `protobuf:"varint,11,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	DateAdded       int64                  `protobuf:"varint,14,opt,name=date_added,json=dateAdded,proto3" json:"date_added,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Release) Reset() {
	*x = Release{}
	mi := &file_discogs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Release) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Release) ProtoMessage() {}

func (x *Release) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Release.ProtoReflect.Descriptor instead.
func (*Release) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{6}
}

func (x *Release) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Release) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *Release) GetFolderId() int32 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

func (x *Release) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Release) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Release) GetMasterId() int64 {
	if x != nil {
		return x.MasterId
	}
	return 0
}

func (x *Release) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Release) GetSleeveCondition() string {
	if x != nil {
		return x.SleeveCondition
	}
	return ""
}

func (x *Release) GetFormats() []*Format {
	if x != nil {
		return x.Formats
	}
	return nil
}

func (x *Release) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Release) GetArtists() []*Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *Release) GetNotes() map[int32]string {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *Release) GetReleaseDate() int64 {
	if x != nil {
		return x.ReleaseDate
	}
	return 0
}

func (x *Release) GetDateAdded() int64 {
	if x != nil {
		return x.DateAdded
	}
	return 0
}

type ReleaseStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MedianPrice   int32                  `protobuf:"varint,1,opt,name=median_price,json=medianPrice,proto3" json:"median_price,omitempty"`
	LowPrice      int32                  `protobuf:"varint,2,opt,name=low_price,json=lowPrice,proto3" json:"low_price,omitempty"`
	HighPrice     int32                  `protobuf:"varint,3,opt,name=high_price,json=highPrice,proto3" json:"high_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStats) Reset() {
	*x = ReleaseStats{}
	mi := &file_discogs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStats) ProtoMessage() {}

func (x *ReleaseStats) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStats.ProtoReflect.Descriptor instead.
func (*ReleaseStats) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseStats) GetMedianPrice() int32 {
	if x != nil {
		return x.MedianPrice
	}
	return 0
}

func (x *ReleaseStats) GetLowPrice() int32 {
	if x != nil {
		return x.LowPrice
	}
	return 0
}

func (x *ReleaseStats) GetHighPrice() int32 {
	if x != nil {
		return x.HighPrice
	}
	return 0
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Catno         string                 `protobuf:"bytes,3,opt,name=catno,proto3" json:"catno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_discogs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{8}
}

func (x *Label) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Label) GetCatno() string {
	if x != nil {
		return x.Catno
	}
	return ""
}

type Price struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Price) Reset() {
	*x = Price{}
	mi := &file_discogs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{9}
}

func (x *Price) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Price) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SaleItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SaleId        int64                  `protobuf:"varint,1,opt,name=sale_id,json=saleId,proto3" json:"sale_id,omitempty"`
	Status        SaleStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=discogs.SaleStatus" json:"status,omitempty"`
	Price         *Price                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	ReleaseId     int64                  `protobuf:"varint,4,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	Condition     string                 `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleItem) Reset() {
	*x = SaleItem{}
	mi := &file_discogs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleItem) ProtoMessage() {}

func (x *SaleItem) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleItem.ProtoReflect.Descriptor instead.
func (*SaleItem) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{10}
}

func (x *SaleItem) GetSaleId() int64 {
	if x != nil {
		return x.SaleId
	}
	return 0
}

func (x *SaleItem) GetStatus() SaleStatus {
	if x != nil {
		return x.Status
	}
	return SaleStatus_UNKNOWN
}

func (x *SaleItem) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *SaleItem) GetReleaseId() int64 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

func (x *SaleItem) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type Artist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artist) Reset() {
	*x = Artist{}
	mi := &file_discogs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artist) ProtoMessage() {}

func (x *Artist) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artist.ProtoReflect.Descriptor instead.
func (*Artist) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{11}
}

func (x *Artist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artist) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Want struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artists       []*Artist              `protobuf:"bytes,3,rep,name=artists,proto3" json:"artists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Want) Reset() {
	*x = Want{}
	mi := &file_discogs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Want) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Want) ProtoMessage() {}

func (x *Want) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Want.ProtoReflect.Descriptor instead.
func (*Want) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{12}
}

func (x *Want) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Want) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Want) GetArtists() []*Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

type OrderItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ReleaseId       int64                  `protobuf:"varint,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	Price           *Price                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Condition       string                 `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	SleeveCondition string                 `protobuf:"bytes,5,opt,name=sleeve_condition,json=sleeveCondition,proto3" json:"sleeve_condition,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_discogs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{13}
}

func (x *OrderItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItem) GetReleaseId() int64 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

func (x *OrderItem) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *OrderItem) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *OrderItem) GetSleeveCondition() string {
	if x != nil {
		return x.SleeveCondition
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Created       int64                  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Total         *Price                 `protobuf:"bytes,5,opt,name=total,proto3" json:"total,omitempty"`
	LastActivity  int64                  `protobuf:"varint,6,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_discogs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{14}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotal() *Price {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *Order) GetLastActivity() int64 {
	if x != nil {
		return x.LastActivity
	}
	return 0
}

type SaleParams struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReleaseId       int64                  `protobuf:"varint,1,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	Condition       string                 `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	SleeveCondition string                 `protobuf:"bytes,3,opt,name=sleeve_condition,json=sleeveCondition,proto3" json:"sleeve_condition,omitempty"`
	Price           float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Comments        string                 `protobuf:"bytes,5,opt,name=comments,proto3" json:"comments,omitempty"`
	AllowOffers     bool                   `protobuf:"varint,6,opt,name=allow_offers,json=allowOffers,proto3" json:"allow_offers,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ExternalId      string                 `protobuf:"bytes,8,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Location        string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	Weight          int32                  `protobuf:"varint,10,opt,name=weight,proto3" json:"weight,omitempty"`
	FormatQuantity  int32                  `protobuf:"varint,11,opt,name=format_quantity,json=formatQuantity,proto3" json:"format_quantity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SaleParams) Reset() {
	*x = SaleParams{}
	mi := &file_discogs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleParams) ProtoMessage() {}

func (x *SaleParams) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleParams.ProtoReflect.Descriptor instead.
func (*SaleParams) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{15}
}

func (x *SaleParams) GetReleaseId() int64 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

func (x *SaleParams) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *SaleParams) GetSleeveCondition() string {
	if x != nil {
		return x.SleeveCondition
	}
	return ""
}

func (x *SaleParams) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SaleParams) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

func (x *SaleParams) GetAllowOffers() bool {
	if x != nil {
		return x.AllowOffers
	}
	return false
}

func (x *SaleParams) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SaleParams) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *SaleParams) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SaleParams) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SaleParams) GetFormatQuantity() int32 {
	if x != nil {
		return x.FormatQuantity
	}
	return 0
}

type SaleStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VgPrice       float32                `protobuf:"fixed32,1,opt,name=vg_price,json=vgPrice,proto3" json:"vg_price,omitempty"`
	GplusPrice    float32                `protobuf:"fixed32,2,opt,name=gplus_price,json=gplusPrice,proto3" json:"gplus_price,omitempty"`
	NmPrice       float32                `protobuf:"fixed32,3,opt,name=nm_price,json=nmPrice,proto3" json:"nm_price,omitempty"`
	GPrice        float32                `protobuf:"fixed32,4,opt,name=g_price,json=gPrice,proto3" json:"g_price,omitempty"`
	VgplusPrice   float32                `protobuf:"fixed32,5,opt,name=vgplus_price,json=vgplusPrice,proto3" json:"vgplus_price,omitempty"`
	MPrice        float32                `protobuf:"fixed32,6,opt,name=m_price,json=mPrice,proto3" json:"m_price,omitempty"`
	FPrice        float32                `protobuf:"fixed32,7,opt,name=f_price,json=fPrice,proto3" json:"f_price,omitempty"`
	PPrice        float32                `protobuf:"fixed32,8,opt,name=p_price,json=pPrice,proto3" json:"p_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleStats) Reset() {
	*x = SaleStats{}
	mi := &file_discogs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleStats) ProtoMessage() {}

func (x *SaleStats) ProtoReflect() protoreflect.Message {
	mi := &file_discogs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleStats.ProtoReflect.Descriptor instead.
func (*SaleStats) Descriptor() ([]byte, []int) {
	return file_discogs_proto_rawDescGZIP(), []int{16}
}

func (x *SaleStats) GetVgPrice() float32 {
	if x != nil {
		return x.VgPrice
	}
	return 0
}

func (x *SaleStats) GetGplusPrice() float32 {
	if x != nil {
		return x.GplusPrice
	}
	return 0
}

func (x *SaleStats) GetNmPrice() float32 {
	if x != nil {
		return x.NmPrice
	}
	return 0
}

func (x *SaleStats) GetGPrice() float32 {
	if x != nil {
		return x.GPrice
	}
	return 0
}

func (x *SaleStats) GetVgplusPrice() float32 {
	if x != nil {
		return x.VgplusPrice
	}
	return 0
}

func (x *SaleStats) GetMPrice() float32 {
	if x != nil {
		return x.MPrice
	}
	return 0
}

func (x *SaleStats) GetFPrice() float32 {
	if x != nil {
		return x.FPrice
	}
	return 0
}

func (x *SaleStats) GetPPrice() float32 {
	if x != nil {
		return x.PPrice
	}
	return 0
}

var File_discogs_proto protoreflect.FileDescriptor

const file_discogs_proto_rawDesc = "" +
	"\n" +
	"\rdiscogs.proto\x12\adiscogs\"+\n" +
	"\x05Field\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\",\n" +
	"\x06Folder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"3\n" +
	"\rMasterRelease\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"6\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05pages\x18\x02 \x01(\x05R\x05pages\"\\\n" +
	"\x06Format\x12\"\n" +
	"\fdescriptions\x18\x01 \x03(\tR\fdescriptions\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\xb1\x01\n" +
	"\x04User\x12&\n" +
	"\x0fdiscogs_user_id\x18\x01 \x01(\x05R\rdiscogsUserId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"user_token\x18\x03 \x01(\tR\tuserToken\x12\x1f\n" +
	"\vuser_secret\x18\x04 \x01(\tR\n" +
	"userSecret\x12%\n" +
	"\x0epersonal_token\x18\x05 \x01(\tR\rpersonalToken\"\x98\x04\n" +
	"\aRelease\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\x03R\n" +
	"instanceId\x12\x1b\n" +
	"\tfolder_id\x18\x03 \x01(\x05R\bfolderId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12\x1b\n" +
	"\tmaster_id\x18\r \x01(\x03R\bmasterId\x12\x1c\n" +
	"\tcondition\x18\b \x01(\tR\tcondition\x12)\n" +
	"\x10sleeve_condition\x18\t \x01(\tR\x0fsleeveCondition\x12)\n" +
	"\aformats\x18\x05 \x03(\v2\x0f.discogs.FormatR\aformats\x12&\n" +
	"\x06labels\x18\x06 \x03(\v2\x0e.discogs.LabelR\x06labels\x12)\n" +
	"\aartists\x18\f \x03(\v2\x0f.discogs.ArtistR\aartists\x121\n" +
	"\x05notes\x18\n" +
	" \x03(\v2\x1b.discogs.Release.NotesEntryR\x05notes\x12!\n" +
	"\frelease_date\x18\v \x01(\x03R\vreleaseDate\x12\x1d\n" +
	"\n" +
	"date_added\x18\x0e \x01(\x03R\tdateAdded\x1a8\n" +
	"\n" +
	"NotesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\fReleaseStats\x12!\n" +
	"\fmedian_price\x18\x01 \x01(\x05R\vmedianPrice\x12\x1b\n" +
	"\tlow_price\x18\x02 \x01(\x05R\blowPrice\x12\x1d\n" +
	"\n" +
	"high_price\x18\x03 \x01(\x05R\thighPrice\"A\n" +
	"\x05Label\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05catno\x18\x03 \x01(\tR\x05catno\"9\n" +
	"\x05Price\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"\xb3\x01\n" +
	"\bSaleItem\x12\x17\n" +
	"\asale_id\x18\x01 \x01(\x03R\x06saleId\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.discogs.SaleStatusR\x06status\x12$\n" +
	"\x05price\x18\x03 \x01(\v2\x0e.discogs.PriceR\x05price\x12\x1d\n" +
	"\n" +
	"release_id\x18\x04 \x01(\x03R\treleaseId\x12\x1c\n" +
	"\tcondition\x18\x05 \x01(\tR\tcondition\",\n" +
	"\x06Artist\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"W\n" +
	"\x04Want\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12)\n" +
	"\aartists\x18\x03 \x03(\v2\x0f.discogs.ArtistR\aartists\"\xa9\x01\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"release_id\x18\x02 \x01(\x03R\treleaseId\x12$\n" +
	"\x05price\x18\x03 \x01(\v2\x0e.discogs.PriceR\x05price\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\x12)\n" +
	"\x10sleeve_condition\x18\x05 \x01(\tR\x0fsleeveCondition\"\xbe\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12(\n" +
	"\x05items\x18\x04 \x03(\v2\x12.discogs.OrderItemR\x05items\x12$\n" +
	"\x05total\x18\x05 \x01(\v2\x0e.discogs.PriceR\x05total\x12#\n" +
	"\rlast_activity\x18\x06 \x01(\x03R\flastActivity\"\xdf\x02\n" +
	"\n" +
	"SaleParams\x12\x1d\n" +
	"\n" +
	"release_id\x18\x01 \x01(\x03R\treleaseId\x12\x1c\n" +
	"\tcondition\x18\x02 \x01(\tR\tcondition\x12)\n" +
	"\x10sleeve_condition\x18\x03 \x01(\tR\x0fsleeveCondition\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x1a\n" +
	"\bcomments\x18\x05 \x01(\tR\bcomments\x12!\n" +
	"\fallow_offers\x18\x06 \x01(\bR\vallowOffers\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\vexternal_id\x18\b \x01(\tR\n" +
	"externalId\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12\x16\n" +
	"\x06weight\x18\n" +
	" \x01(\x05R\x06weight\x12'\n" +
	"\x0fformat_quantity\x18\v \x01(\x05R\x0eformatQuantity\"\xe9\x01\n" +
	"\tSaleStats\x12\x19\n" +
	"\bvg_price\x18\x01 \x01(\x02R\avgPrice\x12\x1f\n" +
	"\vgplus_price\x18\x02 \x01(\x02R\n" +
	"gplusPrice\x12\x19\n" +
	"\bnm_price\x18\x03 \x01(\x02R\anmPrice\x12\x17\n" +
	"\ag_price\x18\x04 \x01(\x02R\x06gPrice\x12!\n" +
	"\fvgplus_price\x18\x05 \x01(\x02R\vvgplusPrice\x12\x17\n" +
	"\am_price\x18\x06 \x01(\x02R\x06mPrice\x12\x17\n" +
	"\af_price\x18\a \x01(\x02R\x06fPrice\x12\x17\n" +
	"\ap_price\x18\b \x01(\x02R\x06pPrice*\x19\n" +
	"\n" +
	"MasterSort\x12\v\n" +
	"\aBY_YEAR\x10\x00*X\n" +
	"\n" +
	"SaleStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bFOR_SALE\x10\x01\x12\b\n" +
	"\x04SOLD\x10\x02\x12\r\n" +
	"\tVIOLATION\x10\x03\x12\t\n" +
	"\x05DRAFT\x10\x04\x12\v\n" +
	"\aEXPIRED\x10\x05B'Z%github.com/brotherlogic/discogs/protob\x06proto3"

var (
	file_discogs_proto_rawDescOnce sync.Once
	file_discogs_proto_rawDescData []byte
)

func file_discogs_proto_rawDescGZIP() []byte {
	file_discogs_proto_rawDescOnce.Do(func() {
		file_discogs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discogs_proto_rawDesc), len(file_discogs_proto_rawDesc)))
	})
	return file_discogs_proto_rawDescData
}

var file_discogs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_discogs_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_discogs_proto_goTypes = []any{
	(MasterSort)(0),       // 0: discogs.MasterSort
	(SaleStatus)(0),       // 1: discogs.SaleStatus
	(*Field)(nil),         // 2: discogs.Field
	(*Folder)(nil),        // 3: discogs.Folder
	(*MasterRelease)(nil), // 4: discogs.MasterRelease
	(*Pagination)(nil),    // 5: discogs.Pagination
	(*Format)(nil),        // 6: discogs.Format
	(*User)(nil),          // 7: discogs.User
	(*Release)(nil),       // 8: discogs.Release
	(*ReleaseStats)(nil),  // 9: discogs.ReleaseStats
	(*Label)(nil),         // 10: discogs.Label
	(*Price)(nil),         // 11: discogs.Price
	(*SaleItem)(nil),      // 12: discogs.SaleItem
	(*Artist)(nil),        // 13: discogs.Artist
	(*Want)(nil),          // 14: discogs.Want
	(*OrderItem)(nil),     // 15: discogs.OrderItem
	(*Order)(nil),         // 16: discogs.Order
	(*SaleParams)(nil),    // 17: discogs.SaleParams
	(*SaleStats)(nil),     // 18: discogs.SaleStats
	nil,                   // 19: discogs.Release.NotesEntry
}
var file_discogs_proto_depIdxs = []int32{
	6,  // 0: discogs.Release.formats:type_name -> discogs.Format
	10, // 1: discogs.Release.labels:type_name -> discogs.Label
	13, // 2: discogs.Release.artists:type_name -> discogs.Artist
	19, // 3: discogs.Release.notes:type_name -> discogs.Release.NotesEntry
	1,  // 4: discogs.SaleItem.status:type_name -> discogs.SaleStatus
	11, // 5: discogs.SaleItem.price:type_name -> discogs.Price
	13, // 6: discogs.Want.artists:type_name -> discogs.Artist
	11, // 7: discogs.OrderItem.price:type_name -> discogs.Price
	15, // 8: discogs.Order.items:type_name -> discogs.OrderItem
	11, // 9: discogs.Order.total:type_name -> discogs.Price
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_discogs_proto_init() }
func file_discogs_proto_init() {
	if File_discogs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discogs_proto_rawDesc), len(file_discogs_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_discogs_proto_goTypes,
		DependencyIndexes: file_discogs_proto_depIdxs,
		EnumInfos:         file_discogs_proto_enumTypes,
		MessageInfos:      file_discogs_proto_msgTypes,
	}.Build()
	File_discogs_proto = out.File
	file_discogs_proto_goTypes = nil
	file_discogs_proto_depIdxs = nil
}
